AllCops:
  NewCops: enable

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Max: 35

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 100
  AllowHeredoc: true

Metrics/AbcSize:
  Enabled: false

Style/OrAssignment:
  Enabled: false
